apiVersion: v2
name: control-tower
description: Unified Model, Tool & GenAI Control Tower â€“ Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - model-risk
  - genai-governance
  - mlops
  - compliance
maintainers:
  - name: Control Tower Team
dependencies:
  - name: postgresql
    version: "16.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: "14.x"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
